"""empty message

Revision ID: 777271101303
Revises: 278fa3461603
Create Date: 2020-08-26 10:00:20.394794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777271101303'
down_revision = '278fa3461603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'password_hash')
    # ### end Alembic commands ###
